network: "mocha"
node_type: "light"
core:
  rpc_url: rpc-mocha.pops.one
  grpc_port: 9090

share:
  useExchange: true
  discovery:
    enabled: true
    # Number of peers to sample for data availability sampling
    sampleSize: 8
    # Minimum number of successful responses required
    minSamples: 2
    # Concurrency limit for data availability sampling
    concurrencyLimit: 6
  light:
    trustedPeers: []
    trustedHeight: 0
    samplingRange: 128
    samplingPeriod: "1s"
    waitForCheckpoint: false

image:
  repository: "ghcr.io/celestiaorg/celestia-node"
  tag: "v0.21.9"
  pullPolicy: IfNotPresent

storage:
  size: "250Gi"

service:
  type: "ClusterIP"
  ports:
    p2p-tcp:
      enabled: true
      port: 2121
      targetPort: 2121
      protocol: TCP
    p2p-udp:
      enabled: true
      port: 2121
      targetPort: 2121
      protocol: UDP
    rpc:
      enabled: true
      port: 26658
      targetPort: 26658
      protocol: TCP

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: "celestia-rpc.dogeos.doge.xyz"
      paths:
        - path: "/"
          pathType: Prefix
  tls:
    - secretName: "celestia-rpc-tls"
      hosts:
        - "celestia-rpc.dogeos.doge.xyz"

resources:
  requests:
    cpu: "500m"
    memory: "2Gi"
  limits:
    cpu: "1000m"
    memory: "4Gi"

rpc:
  auth:
    skipAuth: true
    username: "user"
    password: "password_test"