apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "celestia-node.fullname" . }}-config
  labels:
    {{- include "celestia-node.labels" . | nindent 4 }}
data:
  config.toml: |
    [Node]
    StartupTimeout = "20s"
    ShutdownTimeout = "20s"
    Store = "/home/celestia"

    [Core]
    IP = "{{ trimPrefix "https://" .Values.core.rpc_url }}"
    Port = "{{ .Values.core.grpc_port }}"
    TLSEnabled = false

    [State]
    DefaultKeyName = "my_celes_key"
    DefaultBackendName = "test"

    [P2P]
    Network = "{{ .Values.network }}"
    ListenAddresses = ["/ip4/0.0.0.0/udp/2121/quic-v1/webtransport", "/ip4/0.0.0.0/udp/2121/quic-v1", "/ip4/0.0.0.0/udp/2121/webrtc-direct", "/ip4/0.0.0.0/tcp/2121"]
    AnnounceAddresses = []
    NoAnnounceAddresses = []
    MutualPeers = []
    PeerExchange = false
    [P2P.ConnManager]
      Low = 50
      High = 100
      GracePeriod = "1m0s"

    [RPC]
    Address = "0.0.0.0"
    Port = "26658"
    SkipAuth = {{ default false .Values.rpc.auth.skipAuth }}
    [RPC.Auth]
      Username = "{{ .Values.rpc.auth.username }}"
      Password = "{{ .Values.rpc.auth.password }}"

    [Gateway]
    Address = "localhost"
    Port = "26659"
    Enabled = false

    [Share]
    BlockStoreCacheSize = 128
    UseShareExchange = {{ default true .Values.share.useExchange }}
    [Share.EDSStoreParams]
      RecentBlocksCacheSize = 10
    [Share.ShrExEDSParams]
      ServerReadTimeout = "5s"
      ServerWriteTimeout = "1m0s"
      HandleRequestTimeout = "1m0s"
      ConcurrencyLimit = {{ default 8 .Values.share.discovery.concurrencyLimit }}
      BufferSize = 32768
    [Share.ShrExNDParams]
      ServerReadTimeout = "5s"
      ServerWriteTimeout = "1m0s"
      HandleRequestTimeout = "1m0s"
      ConcurrencyLimit = {{ default 8 .Values.share.discovery.concurrencyLimit }}
    [Share.PeerManagerParams]
      PoolValidationTimeout = "2m0s"
      PeerCooldown = "3s"
      GcInterval = "30s"
      EnableBlackListing = false
    [Share.LightAvailability]
      SampleAmount = {{ default 8 .Values.share.discovery.sampleSize }}
    [Share.Discovery]
      PeersLimit = {{ default 5 .Values.share.discovery.minSamples }}
      AdvertiseInterval = "1h0m0s"

    [Header]
    TrustedHash = ""
    TrustedPeers = []
    [Header.Store]
      StoreCacheSize = 512
      IndexCacheSize = 2048
      WriteBatchSize = 512
    [Header.Syncer]
      TrustingPeriod = "336h0m0s"
    [Header.Server]
      WriteDeadline = "8s"
      ReadDeadline = "1m0s"
      RangeRequestTimeout = "10s"
    [Header.Client]
      MaxHeadersPerRangeRequest = 64
      RangeRequestTimeout = "8s"

    [DASer]
    SamplingRange = {{ default 128 .Values.share.samplingRange }}
    ConcurrencyLimit = {{ default 8 .Values.share.discovery.concurrencyLimit }}
    BackgroundStoreInterval = "10m0s"
    SampleFrom = 1
    SampleTimeout = "2m40s"