apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "celestia-node.fullname" . }}
  labels:
    {{- include "celestia-node.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "celestia-node.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "celestia-node.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: init-dirs
          image: "busybox:latest"
          command:
            - "sh"
            - "-c"
            - |
              chmod 777 /home/celestia && \
              mkdir -p /home/celestia/keys /home/celestia/data && \
              chmod -R 777 /home/celestia
          volumeMounts:
            - name: node-store
              mountPath: /home/celestia
        - name: init-node
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command:
            - "celestia"
          args:
            - "{{ .Values.node_type }}"
            - "init"
            - "--keyring.backend"
            - "test"
          env:
            - name: HOME
              value: "/home/celestia"
            - name: CELESTIA_HOME
              value: "/home/celestia"
          volumeMounts:
            - name: node-store
              mountPath: /home/celestia
      containers:
        - name: celestia-node
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command:
            - "sh"
            - "-c"
          args:
            - |
              cp /config/config.toml /home/celestia/config.toml && \
              celestia {{ .Values.node_type }} start \
                --core.ip {{ trimPrefix "https://" .Values.core.rpc_url }} \
                --core.port {{ .Values.core.grpc_port }} \
                --p2p.network {{ .Values.network }} \
                --keyring.backend test
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "pkill -SIGTERM celestia && sleep 5"]
          env:
            - name: HOME
              value: "/home/celestia"
            - name: CELESTIA_HOME
              value: "/home/celestia"
          volumeMounts:
            - name: node-store
              mountPath: /home/celestia
            - name: node-config
              mountPath: /config
              readOnly: true
          ports:
            - name: p2p-tcp
              containerPort: 2121
              protocol: TCP
            - name: p2p-udp
              containerPort: 2121
              protocol: UDP
            - name: rpc
              containerPort: 26658
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: node-store
          persistentVolumeClaim:
            claimName: {{ include "celestia-node.fullname" . }}-pvc
        - name: node-config
          configMap:
            name: {{ include "celestia-node.fullname" . }}-config