apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "celestia-node.fullname" . }}-pvc
  labels:
    {{- include "celestia-node.labels" . | nindent 4 }}
  annotations:
    pv.beta.kubernetes.io/gid: "1000"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}