apiVersion: v1
kind: Service
metadata:
  name: {{ include "celestia-node.fullname" . }}
  labels:
    {{- include "celestia-node.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "celestia-node.selectorLabels" . | nindent 4 }}
  ports:
    {{- range $key, $value := .Values.service.ports }}
    {{- if $value.enabled }}
    - name: {{ $key }}
      port: {{ $value.port }}
      targetPort: {{ $value.targetPort }}
      protocol: {{ $value.protocol }}
    {{- end }}
    {{- end }}
