apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "celestia-node.fullname" . }}-retain
  labels:
    {{- include "celestia-node.labels" . | nindent 4 }}
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
parameters:
  type: gp3